apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: jsondiff
  name: jsondiff
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jsondiff
  template:
    metadata:
      labels:
        app: jsondiff
    spec:
      containers:
        - image: davutozcan/jsondiff:7
          name: jsondiff
---
kind: Service
apiVersion: v1
metadata:
  name: jsondiff
spec:
  selector:
    app: jsondiff
  type: ClusterIP
  ports:
    - name: httpport
      port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jsondiff
  annotations:
    external-dns.alpha.kubernetes.io/hostname: comparejson.davutozcan.info
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  rules:
    - host: comparejson.davutozcan.info
      http:
        paths:
          - backend:
              service:
                name: jsondiff
                port:
                  number: 80
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - comparejson.davutozcan.info
      secretName: jsondiff
